Add exhibit entity
Iotiq-Erste/culturati-application pull request #12
Opened 2023-07-17 09:37 UTC by yusufzartit

2023-07-17 11:02 UTC, inciotiq requested changes

2023-07-17 11:02 UTC, inciotiq commented on src/main/java/com/iotiq/application/messages/Exhibit/ExhibitRequest.java
> +public record ExhibitRequest(String name, List<ExhibitionItem> items) {
We shouldn't expose the ExhibitionItem entity to the client. This request should accept ExhibitionItem ids and find the corresponding entities in the service.

2023-07-17 11:02 UTC, inciotiq commented on src/main/java/com/iotiq/application/service/ExhibitService.java
> +    public void create(ExhibitRequest request) {
This method should be transactional

2023-07-17 11:02 UTC, inciotiq commented on src/main/java/com/iotiq/application/service/ExhibitService.java
> +    public void update(UUID id, ExhibitRequest request){
This method should be transactional

2023-07-17 12:14 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/ExhibitService.java
> +    public void create(ExhibitRequest request) {
I didn't add "Transactional" annotation because the create function is a single transaction.

2023-07-17 12:14 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/ExhibitService.java
> +    public void update(UUID id, ExhibitRequest request){
I didn't add "Transactional" annotation because the update function is a single transaction.

2023-07-19 11:08 UTC, yusufzartit commented on src/main/java/com/iotiq/application/domain/Exhibit.java
> +    private List<ExhibitionItem> items;
It has been fixed.

2023-07-19 11:08 UTC, yusufzartit commented on src/main/java/com/iotiq/application/messages/Exhibit/ExhibitDto.java
> +public record ExhibitDto(UUID id, String name, List<ExhibitionItem> items) {
It has been fixed.

2023-07-19 11:08 UTC, yusufzartit commented on src/main/java/com/iotiq/application/messages/Exhibit/ExhibitDto.java
> +public record ExhibitDto(UUID id, String name, List<ExhibitionItem> items) {
It has been fixed.

2023-07-19 11:08 UTC, yusufzartit commented on src/main/java/com/iotiq/application/messages/Exhibit/ExhibitRequest.java
> +public record ExhibitRequest(String name, List<ExhibitionItem> items) {
It has been fixed.

2023-07-19 11:09 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/ExhibitService.java
> +    public void create(ExhibitRequest request) {
It has been added.

2023-07-19 11:09 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/ExhibitService.java
> +    public void update(UUID id, ExhibitRequest request){
It has been added.

2023-07-20 10:45 UTC, inciotiq requested changes

2023-07-20 11:03 UTC, inciotiq requested changes
Looks good but we should go over the create and update methods :)

2023-07-21 11:35 UTC, yusufzartit commented on src/main/java/com/iotiq/application/controller/ExhibitController.java
> +    public void create(@RequestBody @Valid ExhibitRequest request) throws Exception {
It has been removed.

2023-07-21 11:36 UTC, yusufzartit commented on src/main/java/com/iotiq/application/domain/Exhibit.java
> +    @JsonIgnore
Annotation has been removed .

2023-07-21 11:42 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/ExhibitService.java
> +        Optional<Exhibit> optionalExhibit = exhibitRepository.findById(exhibitId);
It has been changed.

2023-07-21 11:48 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/ExhibitService.java
> +            throw new IllegalArgumentException("One or more ExhibitionItems not found.");
"EntityNotFoundException" has been used in  the exception.

2023-07-21 11:49 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/ExhibitService.java
> +            throw new IllegalArgumentException("One or more ExhibitionItems not found.");
"EntityNotFoundException" has been used in  the exception.

2023-07-24 09:08 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/ExhibitService.java
> +        exhibitionItemService.updateWithNullExhibit(id);
"updateWithNullExhibit" method has been removed.

2023-07-24 12:45 UTC, oguzIotiq requested changes

2023-07-25 06:32 UTC, yusufzartit commented on src/main/java/com/iotiq/application/controller/ExhibitController.java
> +    public void create(@RequestBody @Valid ExhibitRequest request) {
That's what I did because update/create requests are similar.

2023-07-25 06:34 UTC, yusufzartit commented on src/main/java/com/iotiq/application/controller/ExhibitController.java
> +    public void update(@PathVariable UUID id, @RequestBody @Valid ExhibitRequest request) {
A separate request type is created for the update exhibit.

2023-07-25 06:34 UTC, yusufzartit commented on src/main/java/com/iotiq/application/controller/ExhibitController.java
> +    public void create(@RequestBody @Valid ExhibitRequest request) {
A separate request type is created for the create exhibit.

2023-07-25 06:39 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/ExhibitService.java
> +        List<ExhibitionItem> exhibitionItems = exhibitionItemRepository.findAllByIdIn(request.exhibitionItemIds());
Moved to the beginning of the method.

2023-07-25 06:40 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/ExhibitService.java
> +        // Save the Exhibit in the database
It has been removed.

2023-07-25 06:48 UTC, yusufzartit commented on src/main/java/com/iotiq/application/controller/ExhibitController.java
> +        Exhibit exhibit = exhibitService.getOne(id);
It has been removed.

2023-07-25 06:53 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/ExhibitService.java
> +        getOne(id);
We check whether we have an exhibit item in the DB according to this id.

2023-07-25 08:32 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/ExhibitService.java
> +        getOne(id);
removed fetch method the exhibit before deleting it .

2023-07-25 08:36 UTC, oguzIotiq approved these changes

2023-07-25 11:57 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/ExhibitService.java
> +        List<ExhibitionItem> exhibitionItems = exhibitionItemRepository.findAllByIdIn(request.exhibitionItemIds());
issue # 12 has been opened for her.

2023-07-25 11:58 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/ExhibitService.java
> +            item.setExhibit(exhibit);
We can change it if needed in the future.

2023-07-28 07:53 UTC, inciotiq approved these changes

2023-07-28 07:54 UTC, merged