10 add the facilityorestablishment entity
Iotiq-Erste/culturati-application pull request #14
Opened 2023-07-21 09:07 UTC by yusufzartit

2023-07-24 06:22 UTC, inciotiq requested changes

2023-07-24 06:22 UTC, inciotiq commented on src/main/java/com/iotiq/application/messages/facility/FacilityRequest.java
> +        }
This should be done by using validation annotations

2023-07-24 06:22 UTC, inciotiq commented on src/main/java/com/iotiq/application/messages/facility/FacilityRequest.java
> +public record FacilityRequest(@NotNull @NotEmpty String openingTime, @NotNull @NotEmpty String closingTime) {
Can we use LocalTime for openingTime and closingTime here. You can check if jackson serializers/deserializers support it.

2023-07-24 06:22 UTC, inciotiq commented on src/main/java/com/iotiq/application/messages/facility/FacilityRequest.java
> +public record FacilityRequest(@NotNull @NotEmpty String openingTime, @NotNull @NotEmpty String closingTime) {
Something like this might help: https://www.springcloud.io/post/2022-09/springboot-date-format/#gsc.tab=0
Or there might be annotations that do this

2023-07-24 06:22 UTC, inciotiq commented on src/main/java/com/iotiq/application/service/FacilityOrEstablishmentService.java
> +    public void updateFacilityHours(UUID id, FacilityRequest request) {
```suggestion
    public void update(UUID id, FacilityRequest request) {
```

2023-07-24 06:22 UTC, inciotiq commented on src/main/java/com/iotiq/application/service/FacilityOrEstablishmentService.java
> +    public FacilityOrEstablishment getOneById(UUID id) {
```suggestion
    public FacilityOrEstablishment getOne(UUID id) {
```

2023-07-24 09:27 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/FacilityOrEstablishmentService.java
> +    public void updateFacilityHours(UUID id, FacilityRequest request) {
It has been replaced.

2023-07-24 09:30 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/FacilityOrEstablishmentService.java
> +    public FacilityOrEstablishment getOneById(UUID id) {
Method name has been changed.

2023-07-24 09:44 UTC, yusufzartit commented on src/main/java/com/iotiq/application/messages/facility/FacilityRequest.java
> +        }
The condition has been replaced with validation annotations.

2023-07-24 12:28 UTC, yusufzartit commented on src/main/java/com/iotiq/application/messages/facility/FacilityRequest.java
> +public record FacilityRequest(@NotNull @NotEmpty String openingTime, @NotNull @NotEmpty String closingTime) {
The "String" has been replaced with "LocalTime".

2023-07-28 08:34 UTC, inciotiq requested changes

2023-07-28 08:34 UTC, inciotiq commented on src/main/java/com/iotiq/application/messages/facility/FacilityRequest.java
> +        if (openingTime.isAfter(closingTime)) {
Checking if the closing time is after opening time should be done with validation annotations

2023-07-28 08:34 UTC, inciotiq commented on src/main/java/com/iotiq/application/service/FacilityService.java
> +        getOne(id);
No need to getOne here

2023-07-28 10:18 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/FacilityService.java
> +        getOne(id);
Unnecessary 'getOne' method call has been removed.

2023-07-31 07:30 UTC, yusufzartit commented on src/main/java/com/iotiq/application/messages/facility/FacilityRequest.java
> +        if (openingTime.isAfter(closingTime)) {
It has been fixed.

2023-08-01 13:13 UTC, inciotiq approved these changes

2023-08-01 13:14 UTC, merged