20 imlement a geospatial data service for handling geojson files
Iotiq-Erste/culturati-application pull request #22
Opened 2023-08-01 12:31 UTC by yusufzartit

2023-08-02 06:11 UTC, inciotiq requested changes

2023-08-02 06:11 UTC, inciotiq commented on src/main/java/com/iotiq/application/service/GeoJSONService.java
> +        return "The file has been uploaded successfully.";
You don't need to return a message string here.

2023-08-02 06:11 UTC, inciotiq commented on src/main/java/com/iotiq/application/service/GeoJSONService.java
> +            throw new FileNotFoundException("File not found.");
Can you replace this generic exception with a custom one that extends ApplicationException?

2023-08-02 06:11 UTC, inciotiq commented on src/main/java/com/iotiq/application/controller/GeoJSONController.java
> +            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("File upload error: " + e.getMessage());
All string literals for error messages should reside in the message bundle

2023-08-02 06:11 UTC, inciotiq commented on src/main/java/com/iotiq/application/controller/GeoJSONController.java
> +        } catch (IOException e) {
Instead of catching IO exceptions here, you can catch them in the service method and throw a custom exception extending the ApplicationException class. That way our exception handler will handle the response.

2023-08-02 06:30 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/GeoJSONService.java
> +        return "The file has been uploaded successfully.";
It has been removed.

2023-08-02 07:27 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/GeoJSONService.java
> +            throw new FileNotFoundException("File not found.");
it has been fixed.

2023-08-02 07:28 UTC, yusufzartit commented on src/main/java/com/iotiq/application/controller/GeoJSONController.java
> +        } catch (IOException e) {
It has been fixed.

2023-08-02 07:38 UTC, yusufzartit commented on src/main/java/com/iotiq/application/controller/GeoJSONController.java
> +            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("File upload error: " + e.getMessage());
messages.properties has been used

2023-08-04 10:18 UTC, inciotiq requested changes

2023-08-04 10:18 UTC, inciotiq commented on src/main/java/com/iotiq/application/controller/GeoJSONController.java
> +    @PostMapping("/{tenantName}")
Can we take the tenant name from TenantContext.getCurrentTenant

2023-08-04 10:18 UTC, inciotiq commented on src/main/java/com/iotiq/application/service/GeoJSONService.java
> +    private static final String FILE_DIRECTORY = System.getProperty("user.dir") + "/application/src/main/resources/files/";
Can you move this part to the application-dev.yml file -> "/application/src/main/resources/files/"

2023-08-07 05:39 UTC, yusufzartit commented on src/main/java/com/iotiq/application/exception/GeoJsonFileNotFoundException.java
> +        super(HttpStatus.NOT_FOUND, "file_not_found", Collections.singletonList(message));
It has been fixed.

2023-08-07 05:39 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/GeoJSONService.java
> +            throw new GeoJsonFileOperationException("file_save_error", "exception.geoJsonSaveError", exp);
It has been fixed.

2023-08-07 07:35 UTC, yusufzartit commented on src/main/java/com/iotiq/application/controller/GeoJSONController.java
> +    @PostMapping("/{tenantName}")
It has been fixed.

2023-08-07 07:35 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/GeoJSONService.java
> +    private static final String FILE_DIRECTORY = System.getProperty("user.dir") + "/application/src/main/resources/files/";
It has been fixed.

2023-08-08 06:01 UTC, inciotiq requested changes

2023-08-08 06:01 UTC, inciotiq commented on src/main/java/com/iotiq/application/service/GeoJSONService.java
> +public class GeoJSONService {
Can we change the name of the service to a more descriptive one like; `GeoSpatialDataService`, `MapDataService` etc

2023-08-08 08:43 UTC, yusufzartit commented on src/main/java/com/iotiq/application/controller/GeoJSONController.java
> +        String tenantName = TenantContext.getCurrentTenant();
It has been fixed.

2023-08-09 06:33 UTC, inciotiq requested changes

2023-08-09 06:33 UTC, inciotiq commented on src/main/java/com/iotiq/application/service/GeoSpatialDataService.java
> +    @Value("${file_directory}")
this value does not exist in the yml file.

2023-08-09 06:33 UTC, inciotiq commented on src/main/java/com/iotiq/application/service/GeoSpatialDataService.java
> +            throw new GeoJsonFileOperationException("Problem in save geoJson", exp);
We shouldn't put messages in the code. All messages should go into the message bundle. (I mean the string literal `Problem in save geoJson`)

2023-08-09 06:33 UTC, inciotiq commented on src/main/java/com/iotiq/application/service/GeoSpatialDataService.java
> +                throw new EntityNotFoundException("geoJsonNotFound");
You should just wrap the method that throws the IOException, not all of the code block

2023-08-09 06:33 UTC, inciotiq commented on src/main/java/com/iotiq/application/service/GeoSpatialDataService.java
> +    public String saveGeoJSONFile(MultipartFile file) {
Return value of this function is not used

2023-08-21 07:20 UTC, inciotiq approved these changes

2023-08-21 07:20 UTC, merged