25 add coordinates to exhibitionItem entity
Iotiq-Erste/culturati-application pull request #30
Opened 2023-08-03 06:40 UTC by yusufzartit

2023-08-04 07:59 UTC, mesutiotiq commented on src/main/java/com/iotiq/application/domain/ExhibitionItem.java
> +
i guess, this is an unneeded line

2023-08-04 08:01 UTC, mesutiotiq commented on src/main/java/com/iotiq/application/messages/ExhibitionItemDto.java
> +                exhibitionItem.getTitle(), exhibitionItem.getLatitude(), exhibitionItem.getLongitude());
Please add line breaks, for new params.

2023-08-04 10:42 UTC, inciotiq commented on src/main/java/com/iotiq/application/domain/ExhibitionItem.java
> +    private double latitude;
+1

2023-08-04 10:51 UTC, yusufzartit commented on src/main/java/com/iotiq/application/domain/ExhibitionItem.java
> +
It has been removed.

2023-08-04 11:42 UTC, yusufzartit commented on src/main/java/com/iotiq/application/domain/ExhibitionItem.java
> +    private double latitude;
It has been fixed.

2023-08-07 06:49 UTC, inciotiq commented on src/main/java/com/iotiq/application/domain/Location.java
> +    private double latitude;
Should we change these fields to Double so they can be null?

2023-08-07 06:50 UTC, inciotiq commented on src/main/java/com/iotiq/application/domain/Location.java
> +    private double latitude;
@mesutiotiq

2023-08-08 06:43 UTC, inciotiq requested changes

2023-08-08 06:43 UTC, inciotiq commented on src/main/java/com/iotiq/application/messages/exhibitionItem/ExhibitionItemDto.java
> +public record ExhibitionItemDto(UUID id, String wikiId, String path, String title, Location location) {
Since Location is a database entity can you pass a LocationDto to the frontend so that we're not exposing entities

2023-08-08 06:43 UTC, inciotiq commented on src/main/java/com/iotiq/application/messages/exhibitionItem/ExhibitionItemCreateRequest.java
> +public record ExhibitionItemCreateRequest(String title, String path, Location location) {
Can you change the Location to a LocationRequest

2023-08-09 06:35 UTC, inciotiq requested changes

2023-08-09 06:35 UTC, inciotiq commented on src/main/java/com/iotiq/application/messages/exhibitionItem/ExhibitionItemUpdateRequest.java
> +public record ExhibitionItemUpdateRequest(String title, LocationDto location) {
Can you use a new class called LocationRequest here?

2023-08-09 06:35 UTC, inciotiq commented on src/main/java/com/iotiq/application/messages/exhibitionItem/ExhibitionItemCreateRequest.java
> +public record ExhibitionItemCreateRequest(String title, String path,@NotNull LocationDto location) {
The location can be null while creating the exhibitionItem

2023-08-09 06:35 UTC, inciotiq commented on src/main/java/com/iotiq/application/service/ExhibitionItemService.java
> +        location.setLatitude(request.location().latitude());
We should handle the cases where request.location() is null

2023-08-11 06:45 UTC, inciotiq requested changes

2023-08-11 06:45 UTC, inciotiq commented on src/main/java/com/iotiq/application/messages/location/LocationRequest.java
> +    public static Location from(LocationRequest request) {
This is backwards, you can create a LocationRequest instance from a Location instance in the LocationRequest class but not the other way around. Please map these values somewhere else.

2023-08-21 12:04 UTC, merged