26 add coordinates to navpoint entity
Iotiq-Erste/culturati-application pull request #32
Opened 2023-08-04 06:00 UTC by yusufzartit

2023-08-04 11:18 UTC, inciotiq requested changes

2023-08-04 11:18 UTC, inciotiq commented on src/main/java/com/iotiq/application/domain/NavPoint.java
> +    private double latitude;
See Mesut's comments on the other pull request about adding coordinates. I think we can apply those here, too.

2023-08-07 10:30 UTC, mesutiotiq commented on src/main/java/com/iotiq/application/service/NavPointService.java
> +        navPoint.setLatitude(request.latitude());
In my opinion, we should create LocationRequest and embed to parent requests (like NavPointCreateRequest).

2023-08-07 10:37 UTC, mesutiotiq commented on src/main/java/com/iotiq/application/messages/ExhibitionItemCreateRequest.java
>  package com.iotiq.application.messages;
I think exhibition messages should be moved to exhibition folder like "navpoint"

2023-08-07 11:14 UTC, yusufzartit commented on src/main/java/com/iotiq/application/messages/ExhibitionItemCreateRequest.java
>  package com.iotiq.application.messages;
will fix it in another branch.

2023-08-09 06:39 UTC, inciotiq requested changes

2023-08-09 06:39 UTC, inciotiq commented on src/main/java/com/iotiq/application/controller/NavPointController.java
> +    public void create(@RequestBody @Valid NavPointCreateRequest navPointCreateRequest) {
Can you remove ResponseEntity from other endpoints like you did here?

2023-08-09 06:39 UTC, inciotiq commented on src/main/java/com/iotiq/application/messages/navpoint/NavPointCreateRequest.java
> +public record NavPointCreateRequest(LocationDto location,
Can you use a distinct class called LocationRequest in requests?

2023-08-21 12:23 UTC, inciotiq approved these changes

2023-08-21 12:23 UTC, merged