40 add a register endpoint for users with visitor role
Iotiq-Erste/culturati-application pull request #46
Opened 2023-08-22 07:56 UTC by yusufzartit

2023-08-22 10:59 UTC, inciotiq requested changes

2023-08-22 10:59 UTC, inciotiq commented on src/main/java/com/iotiq/application/service/RegistrationService.java
> +        }
```suggestion
        userRepository.findByAccountInfoUsername(request.username()).orElseThrow(() -> new DuplicateUserDataException("username"));
```

2023-08-22 10:59 UTC, inciotiq commented on src/main/java/com/iotiq/application/service/RegistrationService.java
> +        userRepository.save(user);
Can you call the create method in UserService instead of duplicating the code here

2023-08-23 14:01 UTC, yusufzartit commented on src/main/java/com/iotiq/application/service/RegistrationService.java
> +        userRepository.save(user);
The create method in UserService has been used.

2023-08-31 08:37 UTC, inciotiq approved these changes

2023-08-31 08:37 UTC, merged